version: "3"
services:
  greengrass_demo_image:
    build:
      context: ./
    image: invensense-ros2-cloud:latest
  greengrass_bridge:
    image: invensense-ros2-cloud:latest
    command: ros2 launch greengrass_bridge greengrass_bridge.launch.py ros_topics:=['tdk_robokit_icm42622_py','tdk_robokit_ch101_py','tdk_robokit_ak09918_py','tdk_robokit_ics43434_py','tdk_robokit_icp10101_py','tdk_robokit_ads7052_py','tdk_robokit_camera_py','tdk_robokit_lidar_py'] iot_topics:=['cloud_tdk_robokit_icm42622_py','cloud_tdk_robokit_ch101_py','cloud_tdk_robokit_ak09918_py','cloud_tdk_robokit_ics43434_py','cloud_tdk_robokit_icp10101_py','cloud_tdk_robokit_ads7052_py','cloud_tdk_robokit_camera_py','cloud_tdk_robokit_lidar_py']
    environment:
      - AWS_REGION
      - SVCUID
      - AWS_GG_NUCLEUS_DOMAIN_SOCKET_FILEPATH_FOR_COMPONENT
      - AWS_CONTAINER_AUTHORIZATION_TOKEN
      - AWS_CONTAINER_CREDENTIALS_FULL_URI
    volumes:
      - "/greengrass/v2/ipc.socket:/greengrass/v2/ipc.socket"
    restart: on-failure
